<?php

namespace AppBundle\Repository;

/**
 * FoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoireRepository extends \Doctrine\ORM\EntityRepository
{
}
