<?php

namespace AppBundle\Repository;

/**
 * StandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandRepository extends \Doctrine\ORM\EntityRepository
{
}
