<?php

namespace AppBundle\Repository;

/**
 * UserFoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFoireRepository extends \Doctrine\ORM\EntityRepository
{
}
